- quagga/vty_test.go
By making the server socket blocking and improving the read loop, this
avoids a race where read() would get an EAGAIN and abort before any data
was sent.
Add some more error handling and minor style tweaks while I'm here.
Previously:
$ go test ./quagga -run=TestVTYWrite -count=10 -parallel=1
--- FAIL: TestVTYWrite (0.00s)
vty_test.go:186: Server received []byte{}, want []byte{0x74,
0x68, 0x69, 0x73, 0x20, 0x69, 0x73, 0x20, 0x61, 0x20, 0x74, 0x65, 0x73,
0x74, 0x0}
FAIL
FAIL    github.com/google/seesaw/quagga 0.011s
> Fix vty_test race that made it flaky.

- README.md
- engine/engine_test.go
- engine/testdata/re-ip/config_1.pb
- engine/testdata/re-ip/config_2.pb
- engine/testdata/re-ip/config_3.pb
- engine/testdata/re-ip/config_4.pb
- engine/testdata/re-ip/config_5.pb
- engine/vserver.go
- engine/vserver_test.go
Otherwise the engine can leave configured (and try to act upon) no
longer used VIP addresses.
- When receiving a vserver config update, check that the previously
configured unicast VIP addresses are still needed, and remove them if
not.
- Better document relevant vserver fields.
- Ensure vips and lbVservers maps are in-sync with the interface by
pruning as necessary.
- Implement a stub lb interface for testing that allows introspection of
live configuration.
- Use it to validate state during a re-ip transition.
- Other minor test style cleanup.
> Improve engine tracking of configured VIP addresses.

- ncc/arp.go
When an ARP message is serialized to bytes the target MAC address (`FF:FF:FF:FF:FF`) is used in place of the target IP address.
This fixes it so that the correct struct member is used for the target IP address.
> Fix target IP address in serialized ARP message

- engine/config/config.go
- engine/config/fetcher.go
Currently, config servers must be specified under a google.com domain - remove this restriction since it is impractical for open source use.
> seesaw/engine/config: remove google.com domain restriction for config servers

- ncc/arp.go
As defined at http://www.iana.org/assignments/arp-parameters/arp-parameters.xhtml#arp-parameters-2
> Make the ARP messages reflect the Ethernet type.

- binaries/seesaw_engine/main.go
- test_tools/ncc_test_tool/main.go
[RFC5798](https://tools.ietf.org/html/rfc5798) say.
```
6.1.  Parameters Per Virtual Router
VRID                        Virtual Router Identifier.  Configurable
item in the range 1-255 (decimal).  There
is no default.
```
So, I think zero is a invalid value as VRID.
Best regards,
> fixed: take 1-255 as valid VRID.

- netlink/cfuncs.go
- netlink/message.go
We need to let libnl hold our callback identifier (just a numeric map key),
passed as a C void*. cgo expects C void* params's to get Go unsafe.Pointer
args, but does a runtime check to see if the value points at another Go
pointer.
By adding a C-side wrapper with a pure numeric signature, we no longer have to
use unsafe.Pointer Go side, so we avoid the runtime check.
> Avoiding offending the cgo runtime pointer check.

- healthcheck/core.go
This change is to fix the bug that health state update through RPC only
called once in "for" loop init statement, which renders retry logic
usedless.
> Actually retry when RPC send failure happens (#37)

- engine/vserver_test.go
- healthcheck/dns.go
- healthcheck/http.go
fix `HTTPChecker` request url and fmt verbs
> Make `make test` pass with Go 1.11

- healthcheck/healthcheck_test.go
HTTP request to a https server now gets a 400 Bad Request
Tested:
go ./... passes
> Fix go test in go 1.12

- ncc/sysctl.go
commit 70f4d6e07364ce26b3c622ec40c06bf604874dc6 doesn't fix arp flux
completely on the backup node.
ref:
http: //kb.linuxvirtualserver.org/wiki/Using_arp_announce/arp_ignore_to_disable_ARP
> Set arp_announce and arp_ignore

- engine/sync.go
The lock is held when dialing which blocks all other functions on
syncClient. Adding a timeout can remit it a bit.
> add timeout to syncClient

- engine/core.go
- engine/healthcheck.go
- engine/healthcheck_test.go
- engine/sync.go
- engine/vserver.go
- engine/vserver_test.go
backup doesn't do healthcheck which causes a delay during failover. A
successful healthcheck has to be done before backup is able to server
traffic.
This change implemented healthcheck sync so that backup has the fresh
backend status.
> sync healthcheck status from master to backup

- ha/core.go
`for range` has been acceptable syntax for many Go releases now.
> ha: shorten `for _ = range` to `for range`

- ncc/ip.go
Error returns shouldn't be ignored. While it would be unusual for the ip command to succeed earlier but fail here, that is probably a sign that something bad is happening.
> ncc/ip.go: don't ignore errors

- ncc/iptables.go
In this const block, where the expression is not omitted, implicit repetition does not apply, so the consts aren't of iptAction type. The type must be specified.
> ncc/iptables.go: properly type iptAction consts

- binaries/seesaw_ha/main.go
- common/server/server.go
- engine/core.go
- engine/ipc.go
- engine/vserver.go
- ha/core.go
When there are large number of services, it takes minutes for the engine
main  goroutine to process the config. seesaw_ha will failed to push ha
update to the engine and goes into a crash loop.
This change make seesaw_ha wait longer and have the seesaw_engine main
goroutine process ha state at a higher priority.
> Avoid seesaw_ha crashing when processing large amount of services

- engine/healthcheck.go
- engine/healthcheck_test.go
- engine/ipc.go
- engine/sync.go
- healthcheck/dial.go
- healthcheck/http.go
This commit dedups healthchecks when different vservers are using
the same backends.
optimize http healthcheck to use default dailer when not DSR mode.
disable healthcheck sync but enable healthcheck in backup so that during
a failover, backup doesn't need time to ramp healthchecks
> Dedup healthchecks

- engine/config/notifier.go
- engine/config/notifier_test.go
Large number of services in the new config will choke the engine thread
and cause starvation to other processing.
This change ratelimit number of deleted or created services to 10.
> ratelimit service deletion and creation

- engine/core.go
healthcheck was disabled in backup node. This causes service disruption
during failover because it takes a bit while for all healthcheck to come
up if there are large amounts of services.
This commit stops disabling healthcheck on a backup node.
> always enable healthcheck in backup

- watchdog/service.go
The Format method of time.Time is a simpler way of formatting a timestamp in a particular way, than breaking the components out individually.
> watchdog: use time.Time's Format method

- doc/getting_started.md
Replace 'kerel' with 'kernel' in getting_started.md
> fix_kernel_spelling

- engine/bgp.go
- engine/core.go
- engine/engine_test.go
- engine/healthcheck.go
- engine/vserver.go
- ncc/client/ncc_client.go
- test_tools/ncc_test_tool/main.go
ncc_client was dialing and closing in a circle that caused failure when
large amounts of vservers were all calling ncc_client.
This commit will only connect ncc server once and reuse the same single
connection for all ipc calls from engine. Tests show that it's able to
handle 1000 vservers.
Fixed #48
> use single connection in ncc_client

- binaries/seesaw_engine/main.go
- binaries/seesaw_ha/main.go
- go.mod
- go.sum
- ha/core.go
- ha/ha_test.go
seesaw_engine may exits in two cases:
1. seesaw_engine triggers os.Exit. This is common whenever
log.Fatal/Exit is called.
2. SIGTERM is received.
In both cases seesaw_ha may still keep announcing as master
which causes traffic disruption.
This commit fixes this by watching seesaw engine socket file in
seesaw_ha:
1. os.Exit doesn't clean up so engine socket file is not removed. But
all ipvs services keep working until a new seesaw_engine instance wipes
out previous config. So we remove leftover engine socket file first
thing to exit seesaw_ha before wipe out.
2. SIGTERM will be handled gracefully and engine socket is removed
before exiting. seesaw_ha will notice the deletion and exit together.
> Exit seesaw_ha quickly after seesaw_engine exits

- binaries/seesaw_healthcheck/main.go
- healthcheck/core.go
- healthcheck/healthcheck_test.go
If turned on, healthcheck server will continue to spin up goroutines for
managed checks, but skip the actual healthcheck execution and always
report success back via notification channel.
This is helpful in integration test scenario where backend server
doesn't really exists or functioning.
> Add --dry_run config to healthceck CLI

- engine/ipc.go
Nil context and insufficient access errors can be common values, shared among the IPC methods.
> ipc.go: use common error values

- engine/config/config.go
- engine/config/config_test.go
- engine/config/testdata/vipsubnets2.pb
Instead of ignoring or only logging errors when loading configuration, the errors shoud be propagated up and handled.
The question of whether to mark vservers as broken or to propagate the error remains unanswered in the internal fork, so I leave it unanswered here as well.
> engine/config: propagate errors in protoToCluster

- binaries/seesaw_healthcheck/main.go
- healthcheck/core.go
Expose -fetch_interval to decide how often seesaw_healthcheck fetches
config from seesaw_engine. Default is 15 seconds.
> Make healthcheck config fetch interval configurable

- engine/config/config.go
This break statement was breaking the switch at the end of a case, which has no effect.
The loop assigns priority values to the first two nodes, and does nothing to any remaining nodes. Therefore it may as well break the loop and not just the switch.
> engine/config: break loop, not switch

- engine/config/config.go
- engine/config/config_test.go
- engine/ha.go
- engine/healthcheck.go
- engine/sync.go
- engine/vserver.go
- engine/vserver_test.go
- Remove redundant types in map literals
- De-verbose trailing `if err != nil { return err } return nil`
- Add a couple of missing doc comments
- Add field names in struct literals
- Make some method receiver names consistent
> Resolve some lint warnings

- engine/sync_test.go
Context: It is found in CI pipeline that TestSyncHeartbeats case could fail
occasionally, with the following error message.
```
--- FAIL: TestSyncHeartbeats (6.53s)
sync_test.go:156: Got Desynchronisation sync note
sync_test.go:154: Got sync note Desynchronisation, want Heartbeat
sync_test.go:156: Got Desynchronisation sync note
sync_test.go:156: Got Heartbeat sync note
```
And it is caused by the 3 lines this change is trying to remove.
Analysis: syncClient.poll() triggers an asynchronous rpc call on Poll method,
which may (rarely happen) or may not (most cases) completes before syncClient
got disabled. Should Poll actually succeeded, sync client will then receive an
extra `SNTDesync` note, and fail the test case with the above message.
This change removes the racy lines from the test …
> Fix the race condition in TestSyncHeartbeats test case

- engine/core.go
- engine/sync.go
- engine/sync_test.go
- sync.go: Add time of message to SyncNote, to aid debugging
- various: Set the new Time field
- sync_test.go: Add clarifying comments
- sync_test.go: Clean up some test failure messages
- sync_test.go: Remove named return args on newSyncTest
- sync_test.go: IPv4/v6 distinction not used, so remove arg from newLocalTCPListener
- sync.go: Minor refactor of sync session creation into own method
- sync.go: Cleanup of infinite loop + one-case select -> range over ticker
This upstreams some work by @baptr.
> Improve sync_test.go, add time to SyncNote

- ecu/core.go
- ecu/stats.go
Currently, exporting monitoring metrics would require patching the ecu
package to add the necessary functionality. Exporting the types allows
an implementation to provide a statistics publisher via the ECU config.
This PR also makes a few changes to how ecu/stats.go operates.
> Export stats struct/publisher interface for monitoring

- engine/engine_test.go
- engine/vserver_test.go
- ncc/client/dummy.go
This change colocates dummyNCC implementation to `ncclient` package to
make the package boundary clear.
As part of the change, it also split out the ncclient interface
definition to its own file (client.go). And default implementation to
default.go
Also expoese dummyLBInterface struct details for testing purposes.
> ncclient package cleanup

- binaries/seesaw_engine/main.go
- engine/config/engine.go
- engine/core.go
- ncc/arp.go
- ncc/client/dummy.go
- ncc/client/ncc_client.go
- ncc/lb.go
- ncc/types/ncc_types.go
- test_tools/ncc_test_tool/main.go
This commit adds a flag use_vmac to provide a way not to use vmac.
Machines with the same MAC address can be problematic in certain
scenario like VMs. If not using vmac, it requires GARPs sent for each
service VIPs.
> Support disabling vrrp mac

- engine/vserver.go
- ipvs/ipvs.go
for sh and mh, by default, port is not included in hashing. This is
against intuition.
This commit enables sh-port and mh-port option.
Also enables sh-fallback and mh-fallback, which is helpful when l/u
threshold set for a service.
> enables fallback and port for hashing schedulers

- quagga/bgp.go
Fix: The regular expression of quagga BGP neighbor status check does not match the year unit
> fix: the regular expression of quagga BGP neighbor state not match year

- healthcheck/dial.go
- test_tools/healthcheck_test_tool/main.go
For the golang goroutine scheduler algorithm (GMP model), if the gorouting calls a blocking system call, the current P will not release the current M (thread). If there is another G want to run, a new M (thread) must be created. 
Current tcp health check use syscall.Connect to connect to the target. If there are  many goroutines which call tcp health check at the same time, golang may create thousands of threads. 
Actually, golang runtime has provided the dial package to optimize this issue which will use the netpoll unblocking I/O.
In my test env, I run 100000 goroutine,  golang create nearly 8000 thread which is up to the max thread(10000) that golang can support by default.
With the fix in this PR, the thread number is only about 120.
> optimize the tcp healthcheck to reduce the thread usage

- etc/seesaw/cluster.pb.example
Give radius1-2.example.com a distinct IP address from radius1-1.example.com's IP address.
> cluster.pb.example: fix radius1-2.example.com's IP address.

- .github/workflows/ci.yaml
- README.md
- go.mod
- go.sum
We need to update our dependencies due to some security advisories, however the minimum required version for those dependencies is 1.17.
Unfortunately we can't use 1.17 since that causes panics, so we go with 1.18.
From https://github.com/google/seesaw/actions/runs/4282570034/jobs/7457012337:
```
fatal error: checkptr: converted pointer straddles multiple allocations
```
> Update the required `go` version

- go.mod
- go.sum
Addresses an Uncontrolled Resource Consumption condition on HTTP/2 streams.
> seesaw: Bump `golang.org/x/net` version
